# version: '3.8'

# services:

#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.5.0
#     container_name: zookeeper
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000

#   kafka:
#     image: confluentinc/cp-kafka:7.5.0
#     container_name: kafka
#     depends_on:
#       - zookeeper
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

#   redis:
#     image: redis:7-alpine
#     container_name: redis
#     ports:
#       - "6379:6379"

#   postgres:
#     image: postgres:16-alpine
#     container_name: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: codereview
#       POSTGRES_USER: app
#       POSTGRES_PASSWORD: password123
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: codereview
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webhook-service:
    build: ./webhook-service
    container_name: webhook-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - redis
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_REDIS_HOST: redis
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}

  review-job-service:
    build: ./review-job-service
    container_name: review-job-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - redis
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/codereview
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: password123
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GROQ_API_KEY: ${GROQ_API_KEY}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}

volumes:
  postgres_data: